import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../../components/Navbar/page";
import Header from "../../components/Header/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "King's Travel",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* <Navbar/> */}
        {/* <Header/> */}
        {children}</body>
    </html>
  );
}
